---

- name: install epel-release
  yum:
    name: epel-release
    state: present
    update_cache: true
  when: ansible_os_family | lower == "redhat"

- name: install beanstalkd
  package:
    name: beanstalkd
    state: present
    update_cache: true

- name: setup beanstalkd config
  template:
    src: beanstalkd.j2
    backup: true
    dest: "{{ beanstalkd_config_directory }}/beanstalkd"
    group: root
    owner: root
    mode: 0644
  notify: restart beanstalkd
  when: custom_config_src is not defined

- name: ensure beanstalkd is started
  service:
    name: beanstalkd
    state: started
    enabled: true
